### ISSUE TITLE
[Exercise 2.3] Miscalculated value

### ISSUE THREAD

**Issue by HyeAnn-Lee** [habanoz/reinforcement-learning-an-introduction#1]
https://github.com/habanoz/reinforcement-learning-an-introduction/blob/4801b361f8a9b85fe3670995b9ee88cd46761689/chapter02/exercises2.tex#L101

For average reward part above, the last calculation should be: $= \frac{0.99}{0.9} = 1.1$.

**Comment by habanoz** [comment]
Hi @happy1004ann,

Thanks for pointing out. You are right. I have fixed it.
