### ISSUE TITLE
answer to exercise 2.2 is wrong

### ISSUE THREAD

**Issue by Mostafa-Hamidifard** [habanoz/reinforcement-learning-an-introduction#2]
Hello,
the probability is 0.75 because with p=0.5 greedy action is selected and for p=0.5 an arbitrary action is selected which can be also the greedy one. so overall, it will be 0.5 + 0.5 * 0.5 = 0.75.
please correct it.

**Comment by habanoz** [comment]
Hi @Mostafa-Hamidifard, I think your point is correct. I have modified the solution to exercise 2.1.
Thanks.
